% Script generated by Brainstorm (15-Jan-2019)

% Input files
sFiles = [];

% Start a new report
bst_report('Start', sFiles);

% Process: Coherence NxN
sFiles = bst_process('CallProcess', 'process_cohere1n', sFiles, [], ...
    'timewindow',   [-500, 500], ...
    'removeevoked', 0, ...
    'cohmeasure',   2, ...  % Imaginary
    'maxfreqres',   2, ...
    'maxfreq',      60, ...
    'outputmode',   1);  % Save individual results (one file per input file)

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

