function importEEG_raw(SubjectNames, RawFiles)
    % Script generated by Brainstorm (15-Jan-2019)

    % Input files
    sFiles = [];

    % Start a new report
    bst_report('Start', sFiles);
    
    % Process: Create link to raw file
    sFiles = bst_process('CallProcess', 'process_import_data_raw', sFiles, [], ...
        'subjectname',    SubjectNames{1}, ...
        'datafile',       {RawFiles{1}, RawFiles{1}}, ...
        'channelreplace', 1, ...
        'channelalign',   1, ...
        'evtmode',        'value');

    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    % bst_report('Export', ReportFile, ExportDir);
end

