% path = 'D:\projects\brainstorm_db\eegfmri_london\data';
brainstorm nogui
addpath('D:\projects\git\python-eeg\matlab')

SubjectNames = {'test2'};
RawFilesMRI = {'D:\projects\london\T1\32\32'};
RawFilesEEG = {'D:\projects\london\EEG\32\20130410320002.eeg'};
capLayout = {'D:\projects\london\EEG\generic_64.xyz'};

% Script generated by Brainstorm (15-Jan-2019)
import_fressurfer(subjectNames, RawFilesMRI);
bem_model(subjectNames);

%import EEG data
sFiles = importEEG_raw(subjectNames, RawFilesEEG);

%filter data
sFiles = filterRaw(sFiles);

%load generic EEG coordinates from template
setChannelFile(subjectNames, capLayout);

pause
%manual Coregistration of Electrode Cap to MRI
%manual artifact reject of movement artifacts and bad channels

%import trails/segements
event_name = 'Sync On';
epoch_time = 2.0;
importEvents(sFiles, SubjectNames, event_name, epoch_time)

%manual coregistration or load coregistration
openmeeg_headmodel(subjectNames);

dataCovariance(subjectNames);

sFiles = eegAtlasSources(sFiles, 'Destrieux');

conns = eegConnectivity(sFiles, type);