function setChannelFile(sFiles, RawFiles)
% Script generated by Brainstorm (15-Jan-2019)

% Input files
sFiles = [];

% Start a new report
bst_report('Start', sFiles);

% Process: Set channel file
sFiles = bst_process('CallProcess', 'process_import_channel', sFiles, [], ...
    'channelfile',  {RawFiles{1}, RawFiles{1}}, ...
    'usedefault',   1, ...  % 
    'channelalign', 1, ...
    'fixunits',     1, ...
    'vox2ras',      1);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

