function bem_model(SubjectNames)

    % Script generated by Brainstorm (15-Jan-2019)

    % Input files
    sFiles = [];

    % Start a new report
    bst_report('Start', sFiles);

    % Process: Generate BEM surfaces
    sFiles = bst_process('CallProcess', 'process_generate_bem', sFiles, [], ...
        'subjectname', SubjectNames{1}, ...
        'nscalp',      1922, ...
        'nouter',      1922, ...
        'ninner',      1922, ...
        'thickness',   4);

    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    % bst_report('Export', ReportFile, ExportDir);

end

